config/routes.rb
Rails.application.routes.draw do
  resources :alumnos

end

app/models/alumno.rb
class Alumno < ActiveRecord::Base
end

app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  before_action :set_alumno, only: [:show, :edit, :update, :destroy]

  # GET /alumnos
  # GET /alumnos.json
  def index
    @alumnos = Alumno.all
    @user = "aosorio" #Declaramos una variable y luego la invocamos en el index
  end

  # GET /alumnos/1
  # GET /alumnos/1.json
  def show
  end

  # GET /alumnos/new
  def new
    @alumno = Alumno.new
  end

  # GET /alumnos/1/edit
  def edit
  end

  # POST /alumnos
  # POST /alumnos.json
  def create
    @alumno = Alumno.new(alumno_params)

    respond_to do |format|
      if @alumno.save
        format.html { redirect_to @alumno, notice: '¡Alumno registrado exitosamente!' }
        format.json { render :show, status: :created, location: @alumno }
      else
        format.html { render :new }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnos/1
  # PATCH/PUT /alumnos/1.json
  def update
    respond_to do |format|
      if @alumno.update(alumno_params)
        format.html { redirect_to @alumno, notice: '¡Alumno actualizado exitosamente!' }
        format.json { render :show, status: :ok, location: @alumno }
      else
        format.html { render :edit }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1
  # DELETE /alumnos/1.json
  def destroy
    @alumno.destroy
    respond_to do |format|
      format.html { redirect_to alumnos_url, notice: '¡Alumno eliminado exitosamente!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumno
      @alumno = Alumno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alumno_params
      params.require(:alumno).permit(:nombre, :apellido, :cedula, :correo, :telefono)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alumnos/_form.html.erb
<%= form_for(@alumno) do |f| %>
  <% if @alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alumno.errors.count, "error") %> prohibited this alumno from being saved:</h2>

      <ul>
      <% @alumno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :cedula %><br>
    <%= f.text_field :cedula %>
  </div>
  <div class="field">
    <%= f.label :correo %><br>
    <%= f.text_field :correo %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alumnos/edit.html.erb
<div id="cuerpo">
	<h1>Editando Alumno</h1>
	<%= render 'form' %>
	<%= link_to 'Mostrar', @alumno %> |
	<%= link_to 'Atrás', alumnos_path %>
</div>

app/views/alumnos/index.html.erb
 <!-- La variable declarada en el controlador ahora la veremos en la vista -->
<b>Bienvenido:</b> <%= @user %><br />
<div id="cuerpo">
  <p id="notice"><%= notice %></p>
  <h1>Lista de Alumnos</h1>
  <table border="1px" cellpadding="5px">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Cedula</th>
        <th>Correo</th>
        <th>Telefono</th>
        <th colspan="3">Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @alumnos.each do |alumno| %>
        <tr>
          <td><%= alumno.nombre %></td>
          <td><%= alumno.apellido %></td>
          <td><%= alumno.cedula %></td>
          <td><%= alumno.correo %></td>
          <td><%= alumno.telefono %></td>
          <td><%= link_to 'Mostrar', alumno %></td>
          <td><%= link_to 'Editar', edit_alumno_path(alumno) %></td>
          <td><%= link_to 'Eliminar', alumno, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'Registrar Alumno', new_alumno_path %>
</div>

app/views/alumnos/new.html.erb
<div id="cuerpo">
  <h1>Nuevo Alumno</h1>
  <%= render 'form' %>
  <%= link_to 'Atrás', alumnos_path %>
</div>

app/views/alumnos/show.html.erb
<div id="cuerpo">
  <p id="notice"><%= notice %></p>
  <p>
    <strong>Nombre:</strong>
    <%= @alumno.nombre %>
  </p>
  <p>
    <strong>Apellido:</strong>
    <%= @alumno.apellido %>
  </p>
  <p>
    <strong>Cedula:</strong>
    <%= @alumno.cedula %>
  </p>
  <p>
    <strong>Correo:</strong>
    <%= @alumno.correo %>
  </p>
  <p>
    <strong>Telefono:</strong>
    <%= @alumno.telefono %>
  </p>
  <%= link_to 'Editar', edit_alumno_path(@alumno) %> |
  <%= link_to 'Atrás', alumnos_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Registro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>